export const ACTIONS = {
  INITIALIZE_CATEGORIES: "INITIALIZE CATEGORIES",
  INITIALIZE_PRODUCTS: "INITIALIZE PRODUCTS",
  FILTER_SEARCH: "FILTER SEARCH",
  FILTER_PRICE: "FILTER PRICE",
  FILTER_CATEGORY: "FILTER CATEGORY",
  FILTER_RATINGS: "FILTER RATINGS",
  FILTER_SORT: "FILTER SORT",
  FILTER_CLEAR_FILTER: "CLEAR FILTERS",
};
