export const ACTIONS = {
  INITIALIZE_CATEGORIES: "INITIALIZE CATEGORIES",
  INITIALIZE_PRODUCTS: "INITIALIZE PRODUCTS",
  FILTER_SEARCH: "FILTER SEARCH",
  FILTER_PRICE: "FILTER PRICE",
  FILTER_CATEGORY: "FILTER CATEGORY",
  FILTER_RATINGS: "FILTER RATINGS",
  FILTER_SORT: "FILTER SORT",
  FILTER_CLEAR_FILTER: "CLEAR FILTERS",
  ADD_TO_WISHLIST: "ADD TO WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE FROM WISHLIST",
  ADD_TO_CART: "ADD TO CART",
  REMOVE_FROM_CART: "REMOVE FROM CART",
};
